### ISSUE TITLE
Missing icons 

### ISSUE THREAD

**Issue by Guray00** [Syoker/ExtraThemedIcons#1]
Hi, can you please add:
- notesnook 
- Todoist

Or add in readme how to contribute with this project? 
Thanks in advance!

**Comment by syoker** [comment]
Hi, these icons are not mine, the module is just a collection of icons to install them on your system.
If you want these icons, here's where to request them from the icons' authors

TeamFiles: https://t.me/iconrequestsbot
Lawnchair: https://github.com/LawnchairLauncher/lawnicons/issues

Thanks for writing.
