### ISSUE TITLE
Does it only work on AOSP / Pixel launcher?

### ISSUE THREAD

**Issue by noelje** [Syoker/ExtraThemedIcons#2]
I have a rooted device running LineageOS 19 (based on Android 12). 

When I installed the module in Magisk (v25) and rebooted, nothing happened and no app was installed. 

The README is unclear on how to proceed after installation.

**Comment by syoker** [comment]
Themed icons will only work in the Pixel Launcher or 3rd party launchers that work the same as the Pixel Launcher.

To test if it works, go to the "styles" section of the launcher, and look for the "themed icons" option, activate it and check the apps in home.

This module does not install an app, it installs an overlay with icons, so no app will appear in the app drawer. And the functionality is the same as in Pixels, the themed icons will only be applied in the home, not in the app drawer.

https://user-images.githubusercontent.com/61765318/202742817-e0e317ff-d923-4ec9-a1fc-79571ff475c2.mp4

**Comment by noelje** [comment]
Doesn't work with my ROM. But thank you for your response and for making this module! :)
